2023-08-22 00:21:18 | Traceback (most recent call last):
  File "c:\Users\smykr\Desktop\class employee with try except.py", line 51, in validate
    raise EmailAlreadyExistsException("Email already exists")
EmailAlreadyExistsException: Email already exists

2023-08-22 00:21:18 | Traceback (most recent call last):
  File "c:\Users\smykr\Desktop\class employee with try except.py", line 51, in validate
    raise EmailAlreadyExistsException("Email already exists")
EmailAlreadyExistsException: Email already exists

2023-08-22 00:21:18 | Traceback (most recent call last):
  File "c:\Users\smykr\Desktop\class employee with try except.py", line 51, in validate
    raise EmailAlreadyExistsException("Email already exists")
EmailAlreadyExistsException: Email already exists

2023-08-22 00:21:18 | Traceback (most recent call last):
  File "c:\Users\smykr\Desktop\class employee with try except.py", line 51, in validate
    raise EmailAlreadyExistsException("Email already exists")
EmailAlreadyExistsException: Email already exists

